# Generated by Django 5.0.3 on 2024-03-10 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('planet', models.CharField(default='Earth', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
