# Generated by Django 5.0.3 on 2024-03-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('start_time', models.DateTimeField(db_column='from')),
                ('end_time', models.DateTimeField(db_column='to')),
            ],
        ),
    ]
