# Generated by Django 5.0.3 on 2024-03-09 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('sc_id', models.AutoField(primary_key=True, serialize=False)),
                ('planet', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedReport',
            fields=[
                ('rec_rep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('absolut_path', models.CharField(max_length=255)),
                ('scientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.scientist')),
            ],
        ),
        migrations.CreateModel(
            name='SentReport',
            fields=[
                ('sent_rep_id', models.AutoField(primary_key=True, serialize=False)),
                ('character_count_max', models.IntegerField()),
                ('character_count_sent', models.IntegerField()),
                ('absolut_path', models.CharField(max_length=255)),
                ('scientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.scientist')),
            ],
        ),
    ]
